### PR TITLE
Support arm64 and arm

### PR DESCRIPTION
**Pull request by tnasu**
## Description

- Just enabled to support `arm64`and `arm`
- Refactored job names on `github actions`

### CODE REVIEW

**Review by torao — APPROVED** [review]
LGTM

**Review by kokeshiM0chi — APPROVED** [review]
LGTM

**Comment by torao** [comment]
Where are arm64 builds tested in CircleCI?

**Comment by tnasu** [comment]
I always use [act](https://github.com/nektos/act) for `github actions test` in local.

Example commands.
```bash

// hock=pull_request, job=build-linux
act pull_request -j build-linux -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest

// hock=push, job=build-docker
act push -j build-docker -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
```

JFY: 
`ubuntu-latest` usually use `Micro Docker Image = node:12-buster-slim` in local
- https://github.com/nektos/act#runners

So I specify `P` and use `Medium Docker Image = ghcr.io/catthehacker/ubuntu:act-latest`
```
  -P, --platform stringArray             custom image to use per platform (e.g. -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04)
```

**Pull request merged**
