### PR TITLE
Support for VRF implementation with libsodium

### PR DESCRIPTION
**Pull request by torao**
## Description

This PR supports the use of libsodium in addition to r2ishiguro, which has been used in Ostracon so far. Note that the build-time default is still r2ishiguro. Setting `LIBSODIUM=1` at build or test time will enable libsodium. The fix to make the build default to libsodium is in another PR.

## Note

In v0.34.8, I found a bug that when restoring Evidence from `evidencePool`, it failed to [unmarshal as `tmproto.LightClientAttackEvidence`](https://github.com/tendermint/tendermint/blob/v0.34.8/evidence/pool.go#L273-L274) because it was [marshaled by `tmproto.Evidence`](https://github.com/tendermint/tendermint/blob/v0.34.8/evidence/pool.go#L353-L358). This bug has been fixed in v0.34.11. Unfortunately, there were two checks [(1)](https://github.com/tendermint/tendermint/blob/v0.34.8/evidence/pool_test.go#L306-L308) and [(2)](https://github.com/tendermint/tendermint/blob/v0.34.8/evidence/verify_test.go#L125-L127) that happened to work correctly due to the side effects of this bug. Since these checks don't appear to have the correct semantics and have been removed in v0.34.11, I remove them in this PR. Related PR in Tendermint is https://github.com/tendermint/tendermint/pull/6375.

Closes: #XXX

### CODE REVIEW

**Review by tnasu — CHANGES_REQUESTED** [review]
I'm not sure that the changing of `submodules: recursive` help to make the next PR of `default libsodium`. For example, should we add new tasks like `build-linux` task on `.github/workflows/coverage.yml`? And should it depends on `Makefile` tasks since it's easy to build with `libsodium`?

**Review by kokeshiM0chi — DISMISSED** [review]
LGTM

**Review by tnasu — APPROVED** [review]
LGTM

**Review by kokeshiM0chi — APPROVED** [review]
LGTM

**Pull request merged**
